import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Head from "next/head";
import ShoppingCart from "./context/ShoppingCartProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shop.co",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head></Head>
      <html lang="en">
        <body className={inter.className}>
          <main className="">
            <ShoppingCart>
              <NavBar />
              <div className="body">{children}</div>
              <Footer />
            </ShoppingCart>
          </main>
        </body>
      </html>
    </>
  );
}
